### ISSUE TITLE
Ethernet Cloud? Access-Control-Allow-Orgin

### ISSUE THREAD

**Issue by cormacwat** [marcoschwartz/aREST.js#2]
Hi I'm using aRest for an online application and I was wondering if the javascript is compatible with the cloud service yet? The examples asks for an IP address and I was wondering if it was just a matter of giving the cloud address in its place?
Edit: I've gone ahead and done the above and it seems to be attempting to make a request to my cloud address but I'm getting this error 
`XMLHttpRequest cannot load http://cloud.arest.io/Arduino_ID/temperature. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access`

which is blocking the request, Is there any workaround that I could implement to avoid this or does work have to be completed on the cloud side?

**Comment by marcoschwartz** [comment]
Hi! In theory this is possible, however it's not supported yet. I will work on it, marking this as a feature request :)

**Comment by marcoschwartz** [comment]
That's now fixed with the latest update of the cloud server, the correct headers are now sent :)
