### ISSUE TITLE
Call all variables at once

### ISSUE THREAD

**Issue by klerone** [marcoschwartz/aREST.js#3]
Hi Marco.

I have been using this library, it's really useful and easy to implement, You made a great job. I wonder if there is any way to get all the variable from a device in one AJAX call?

I implemented this in my own way, since is see in the fast test example can get all the information at once when browse to ex. 192.186.1.101/"my_id", using standard Java Script I get the data in one call to save time, but I wonder if you made any command for this and just I didn't read it.

**Comment by marcoschwartz** [comment]
Hi, thanks! Sure you can, you simple need to call the IP address without any arguments, for example:

192.186.1.101

Note that it only works in local for now, for the cloud access (via aREST.io) there is a problem at the moment because of the MQTT packet size that I can't change.
