### ISSUE TITLE
Device ONLINE or OFFLine

### ISSUE THREAD

**Issue by klerone** [marcoschwartz/aREST.js#4]
Hi Marco.

I really love this library, you saved me a lot of time to keep going with my homebrew smart home system.

I found troubles when trying to get if my devices are online or offline, here is how o get to solve it.

In the aREST.js file:
`this.getVariable = function(variable, callback) {    
    $.ajaxq('queue', {
      url: 'http://' + this.address + '/' + variable + $.now(),
      cache: false,
      crossDomain: true
    }).done(function(data) {
      callback(data);
      console.log('Success!: peticion enviada')
    })
    //Esto permite verificar si el dispositivo esta online u offline
    // agregado por Fran Calero.
    .fail(function(data) { 
       data = false;
       callback(data);
       console.log('Error: dispositivo fuera de linea.');
    });
 };` 

Since it's easy to get the online status, was quite hard for me  (I'm new with web development)  to get the device status and I wanted to get in real time if my device where online or offline automatically.
I set the answer from the ajax callback function to false to get it work smooth and handle the answer inside the script.js file.

**Comment by marcoschwartz** [comment]
Well, as the device won't send any message automatically to aREST.js when it comes offline or online, you'll need to check periodically with ajax calls to see what's the status of the device in 'real time'. For that, I suggest using a setInterval function that will check that at regular intervals. Was that your question?

**Comment by klerone** [comment]
Thank you I manage to solve the problem, but what I meant is that when calling the function can get the online status but if it's offline don't return anything but I get it work adding this lines of code:
`.fail(function(data) { data = false; callback(data); console.log('Error: dispositivo fuera de linea.'); });` 
with that can handle the error response a bit more easy

**Comment by marcoschwartz** [comment]
Excellent, good to hear you solved your problem :)
